#!/bin/bash
rm -rf "Data/"
mkdir -p "Data/EG1/OmegaRotPS/"
mkdir -p "Data/EG1/OmegaTGPSPS/"
mkdir -p "Data/EG1/OmegaTGPSPlusPS/"
mkdir -p "Data/EG1/Pi0RotPS/"
mkdir -p "Data/EG1/Pi0TGPSPlusPS/"
mkdir -p "Data/EG1/OmegaRotWOPS/"
mkdir -p "Data/EG1/OmegaTGPSWOPS/"
mkdir -p "Data/EG1/OmegaTGPSPlusWOPS/"
mkdir -p "Data/EG1/OmegaTGPSPlusAPPS1Sigma/"
mkdir -p "Data/EG1/OmegaTGPSPlusAPPS2Sigma/"
mkdir -p "Data/EG1/OmegaTGPSPlusAPPS3Sigma/"
mkdir -p "Data/EG1/Comp/"

mkdir -p "Data/EG2/OmegaRotPS/"
mkdir -p "Data/EG2/OmegaTGPSPS/"
mkdir -p "Data/EG2/OmegaTGPSPlusPS/"
mkdir -p "Data/EG2/Pi0RotPS/"
mkdir -p "Data/EG2/Pi0TGPSPlusPS/"
mkdir -p "Data/EG2/OmegaRotWOPS/"
mkdir -p "Data/EG2/OmegaTGPSWOPS/"
mkdir -p "Data/EG2/OmegaTGPSPlusWOPS/"
mkdir -p "Data/EG2/OmegaTGPSPlusAPPS1Sigma/"
mkdir -p "Data/EG2/OmegaTGPSPlusAPPS2Sigma/"
mkdir -p "Data/EG2/OmegaTGPSPlusAPPS3Sigma/"
mkdir -p "Data/EG2/Comp/"

./install/plot
